// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2231.Robot2013.commands;

import edu.wpi.first.wpilibj.CANTalon.TalonControlMode;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc2231.Robot2013.Robot;
import org.usfirst.frc2231.Robot2013.RobotMap;
import org.usfirst.frc2231.Robot2013.StaticMembers;
import org.usfirst.frc2231.Robot2013.StickButtons;

import FRC_Vision2016_newMethods_ft_team2231.*;
/**
 *
 */
public class CenterByVision extends Command {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
	double m_setpoint;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public CenterByVision(double setpoint) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
    	m_setpoint = setpoint;
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.driveTrain.changeTalonControlMode(TalonControlMode.Follower);
    	RobotMap.visionSensor.setPIDVisionSourceType(PIDVisionSourceType.NormalizedDistanceFromCenter);
		RobotMap.visionSensor.refreshValues();
    	RobotMap.VisionRotateLeftPIDController.setSetpoint(m_setpoint);
    	RobotMap.VisionRotateRightPIDController.setSetpoint(m_setpoint);
    	if(RobotMap.VisionRotateLeftPIDController.onTarget(StaticMembers.ABSOLUTE_TOLERANCE_ROTATION) && RobotMap.VisionRotateRightPIDController.onTarget(StaticMembers.ABSOLUTE_TOLERANCE_ROTATION)){
    		return;
    	}
    	RobotMap.VisionRotateLeftPIDController.enable();	
    	RobotMap.VisionRotateRightPIDController.enable();	
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	RobotMap.visionSensor.refreshValues();
    	System.out.println("Vision error: " + RobotMap.VisionRotateLeftPIDController.getError() +  " , " + RobotMap.VisionRotateRightPIDController.getError());
		System.out.println("vision, pidcontroller output: " + RobotMap.VisionRotateLeftPIDController.get() + " , " + RobotMap.VisionRotateRightPIDController.get());		    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	boolean isLeftOnTarget = RobotMap.VisionRotateLeftPIDController.onTarget(StaticMembers.ABSOLUTE_TOLERANCE_ROTATION);
    	boolean isRightOnTarget = RobotMap.VisionRotateRightPIDController.onTarget(StaticMembers.ABSOLUTE_TOLERANCE_ROTATION);
		return isLeftOnTarget && isRightOnTarget;    	
    
    }

    // Called once after isFinished returns true
    protected void end() {
    	RobotMap.visionSensor.refreshValues();
    	System.out.println("pid Get" + RobotMap.visionSensor.pidGet());
		RobotMap.VisionRotateLeftPIDController.reset();
    	RobotMap.VisionRotateRightPIDController.reset();
		RobotMap.VisionRotateLeftPIDController.disable();
		RobotMap.VisionRotateRightPIDController.disable();
    	Robot.driveTrain.resetTalonControlMode();
    	RobotMap.VisionRotateLeftPIDController.disableWriting();
    	RobotMap.visionSensor.resetValues();
		System.out.println("centered by vision");
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
		RobotMap.VisionRotateLeftPIDController.reset();
    	RobotMap.VisionRotateRightPIDController.reset();
		RobotMap.VisionRotateLeftPIDController.disable();
		RobotMap.VisionRotateRightPIDController.disable();
    	Robot.driveTrain.resetTalonControlMode();
    	RobotMap.VisionRotateLeftPIDController.disableWriting();
    	RobotMap.visionSensor.resetValues();
    	System.out.println("center by vision has been interrupted");
    }
}
