// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2231.Robot2013.commands;

import edu.wpi.first.wpilibj.CANTalon.TalonControlMode;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc2231.Robot2013.Robot;
import org.usfirst.frc2231.Robot2013.RobotMap;
import org.usfirst.frc2231.Robot2013.StaticMembers;

import FRC_Vision2016_newMethods_ft_team2231.PIDVisionSourceType;

/**
 *
 */
public class DriveForwardByVision extends Command {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
	private double m_setPoint;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	public DriveForwardByVision(double setPoint) {

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
		m_setPoint = setPoint;

		// RobotBuilder Version: 2.0
		//
		// This file was generated by RobotBuilder. It contains sections of
		// code that are automatically generated and assigned by robotbuilder.
		// These sections will be updated in the future when you export to
		// Java from RobotBuilder. Do not put any code or make any change in
		// the blocks indicating autogenerated code or it will be lost on an
		// update. Deleting the comments indicating the section will prevent
		// it from being updated in the future.

		requires(Robot.driveTrain);

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	}

	// Called just before this Command runs the first time
	protected void initialize() {
		RobotMap.visionSensor.refreshValues();
		RobotMap.visionSensor.setPIDVisionSourceType(PIDVisionSourceType.DistanceFromTarget);
		Robot.driveTrain.changeTalonControlModeForward(TalonControlMode.Follower);
		RobotMap.VisionLeftPIDController.setSetpoint(m_setPoint);
		RobotMap.VisionLeftPIDController.enable();
	}

	// Called repeatedly when this Command is scheduled to run
	protected void execute() {
		RobotMap.visionSensor.refreshValues();
		System.out.println("Vision, pid Get" + RobotMap.visionSensor.pidGet());

	}

	// Make this return true when this Command no longer needs to run execute()
	protected boolean isFinished() {
		return RobotMap.VisionLeftPIDController.getError() >= Math.abs(StaticMembers.ABSOLUTE_TOLERANCE);
	}

	// Called once after isFinished returns true
	protected void end() {
		Robot.driveTrain.changeTalonControlModeForward(TalonControlMode.PercentVbus);
		System.out.println("On target");
		RobotMap.VisionLeftPIDController.reset();
		RobotMap.VisionLeftPIDController.disable();

	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted() {
		end();
	}
}
